custom:
  kafka-url: ${KAFKA_URL}
server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@119.192.172.145:61004:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: c##deep
    password: qwer1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE